/**
 * Cross-language fixture corpus tests.
 *
 * The fixtures in `packages/notary/fixtures/` are generated by
 * `scripts/gen-fixtures.ts` and consumed by both this TypeScript
 * test and the equivalent Python test in
 * `packages/notary-py/tests/test_fixtures.py`. They are the
 * dogfooding contract: any divergence between the two
 * implementations fails CI.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect } from 'vitest';

import { canonicalise } from '../src/canonicalise';
import { computeChainHash } from '../src/chain';
import { sha256 } from '../src/hash';
import { computeRecordHash } from '../src/record';

const fixturesDir = join(__dirname, '..', 'fixtures');

function loadFixture<T>(file: string): T {
  return JSON.parse(readFileSync(join(fixturesDir, file), 'utf8')) as T;
}

describe('fixtures/canonicalise.json', () => {
  const { cases } = loadFixture<{
    cases: Array<{ name: string; input: unknown; expected: string }>;
  }>('canonicalise.json');

  for (const fixture of cases) {
    it(fixture.name, () => {
      expect(canonicalise(fixture.input)).toBe(fixture.expected);
    });
  }
});

describe('fixtures/hash.json', () => {
  const { cases } = loadFixture<{
    cases: Array<{ input: string; expected: string }>;
  }>('hash.json');

  for (const fixture of cases) {
    it(`sha256(${fixture.input.length} bytes)`, () => {
      expect(sha256(fixture.input)).toBe(fixture.expected);
    });
  }
});

describe('fixtures/record-hash.json', () => {
  const { cases } = loadFixture<{
    cases: Array<{ name: string; payload: Record<string, unknown>; expected: string }>;
  }>('record-hash.json');

  for (const fixture of cases) {
    it(fixture.name, () => {
      expect(computeRecordHash(fixture.payload)).toBe(fixture.expected);
    });
  }
});

describe('fixtures/chain.json', () => {
  const { cases } = loadFixture<{
    cases: Array<{ name: string; recordHash: string; previousHash: string; expected: string }>;
  }>('chain.json');

  for (const fixture of cases) {
    it(fixture.name, () => {
      expect(computeChainHash(fixture.recordHash, fixture.previousHash)).toBe(fixture.expected);
    });
  }
});
